import avatarImg from '@renderer/assets/image/avatar.png';

/**
 * 默认用户信息
 */
export const defaultUserInfo: UserInfo = {
  avatar: avatarImg,
  own_user: '',
  dep_id: '',
  dep_name: '',
  org_id: '',
  org_name: '',
  created_on: '',
  modified_on: '',
  is_dis: false,
  files: [],
  imgs: [],
  id: '',
  int_id: 0,
  uint_id: 0,
  login_name: '',
  open_id: '',
  card: '',
  user_code: '',
  name: '',
  sex: '',
  mobile_phone: '',
  work_place: '',
  id_card_type: '',
  id_card: '',
  enter_time: '',
  posi_time: '',
  leave_time: '',
  contract_type: '',
  contract_begin: '',
  contract_end: '',
  birthday: '',
  dwelling: '',
  is_attend: false,
  attend_no: '',
  is_full_attend: false,
  is_check: false,
  is_salary: false,
  is_virtual: false,
  sort: 0,
  remark: '',
  role_name: '',
  role_id: [],
  createdOn: '',
  lastLoginTime: ''
};
